library(caTools)
library(randomForest)
letterrec <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/letter-recognition/letter-recognition.data", header = FALSE,stringsAsFactors = TRUE)
letterrec$V17 <- as.integer(as.factor(letterrec$V17))
l <- c()
for (x in 1:100)
{
  split <- sample.split(letterrec$V17, SplitRatio = 0.25)
  train_set <- subset(letterrec, split == "TRUE")
  test_set <- subset(letterrec, split == "FALSE")
  model <- randomForest(formula = V1 ~ ., data = train_set)
  predict <- predict(model, test_set)
  cm <- table(predict, test_set[, 1])
  print(cm)
  p <- sum(diag(cm)) / sum(cm)
  l <- append(l, p)
}
sd(l)
mean(l)